### ISSUE TITLE
FoxyTab

### ISSUE THREAD

**Issue by erosman** [erosman/extension-translations#14]
Hi everyone

v2.11 is ready for release if you don't mind updating the translation.
Thank you.

@yfdyh000 
@felixhuang72 
@strel

**Comment by strel** [comment]
Suggestions:
- Translation for Themes section fields placeholders.
- Translation for whole Help.

**Comment by erosman** [comment]
> Translation for Themes section fields placeholders.
Possible, but these are the only ones (the rest are keywords)
- Theme Name
- About Your Theme
- Version
- Your name

> Translation for whole Help.
That would be a big job for the translator and because it gets updated often it needs often updates.

That would also be complicated if it is going to be internationalised automatically. That means if one translations is made and another not, then the other one wont see the help.

The other option is to create multiple helps in multiple languages.

However, if anyone translates the Help, I can include it as a separate file. i.e.

**Help**
- English
- Spanish

Please note that the HTML of the Help should be intact.

**Comment by strel** [comment]
English help, where it says:

"Similar tot he built-in "Close Tab to the Right" [...]"
should say
"Similar to the built-in "Close Tabs to the Right" [...]"

"[...] only tabs with URL starting with http/ftp will be moved. ]

**Comment by strel** [comment]
In english Help, where it says:

"Similar tot he built-in "Close Tab to the Right" [...]"
should say
"Similar to the built-in "Close Tabs to the Right" [...]"

"[...] tabs are closed in target window and the same URL is opened in the current window [...]
probably should say
"[...] tabs are closed in target window and the same URLs are opened in the current window [...]

"[...] only tabs with URL starting with http/ftp will be moved. [...]"
probably should include https, not sure about sftp o ftps

"[...] (it doesn't show it on Options page at the moment."
probably should say
"[...] (it doesn't show it on Options page at the moment)."

"[...] Click 'Save" to apply [...]
probably should say
"[...] Click "Save" to apply [...]

**Comment by strel** [comment]
Here help file in spanish:

[help.zip](https://github.com/erosman/extension-translations/files/1670558/help.zip)

**Comment by erosman** [comment]
> "Similar tot he built-in "Close Tab to the Right" [...]"

Already fixed in 2.11

> "[...] tabs are closed in target window and the same URLs are opened in the current window [...]

Done

> "[...] only tabs with URL starting with http/ftp will be moved. [...]"

HTTPS also starts with http, but OK,

> "[...] (it doesn't show it on Options page at the moment)."

Yes.. but the new versions showed it, is I removed it now.

> "[...] Click "Save" to apply [...]

Done

Thank you
