### ISSUE TITLE
Copy As Plain Text - Add a feature

### ISSUE THREAD

**Issue by ticao2** [erosman/extension-translations#31]
Copy As Plain Text - Add a feature
Just by pausing the mouse on a link, without selecting the text, allow the link text to be copied.
Not the link, just the link text.
That way I can stop using the Copy Link Text addon.

Sorry if I'm in the wrong place, but I did not figure out another way to communicate with you.

**Comment by erosman** [comment]
I have another addon **FoxyLink** which deals with links although that doesn't have the feature to copy link-text yet but it can be added.

**Copy PlainText** (**Copy As Plain Text** is the name of another addon) only deals with selection so something must be selected.

**Comment by ticao2** [comment]
The names are very similar. Sorry for my confusion.
