### ISSUE TITLE
Copy PlainText: locale directory on Windows

### ISSUE THREAD

**Issue by ruzh31** [erosman/extension-translations#51]
Hello! I am using Firefox 91 and Windows 11. I have created a localization file messages.json. What directory should the locale be placed in?

**Comment by erosman** [comment]
Which add-on?
Which language?

**Comment by ruzh31** [comment]
language

**Comment by erosman** [comment]
here:
https://github.com/erosman/extension-translations/blob/master/Copy%20PlainText/ru/messages.json

**Comment by ruzh31** [comment]
I mean a directory on Windows

**Comment by erosman** [comment]
Do you want to add the translation to the add-on that is installed on your Firefox? 
That is not possible. 

Translations must be packed with the addon.

**Comment by ruzh31** [comment]
Ok, thanks!
