### ISSUE TITLE
firemonkey totally unable to inect script on gist.githubusercontent.com

### ISSUE THREAD

**Issue by ale82to** [erosman/extension-translations#76]
i ve created a dead simple userscript:
code : 
// ==UserScript==
// @name gitbutton
// @match            *://*/*
// @version          1.0
// @inject-into content
// ==/UserScript==
  alert("notWorking");
  const fileName = window.location.pathname.split('/').pop();
  const downloadButton = document.createElement('a');
  downloadButton.textContent = 'Download';
  downloadButton.style.display = 'inline-block';
  downloadButton.style.margin = '10px';
  downloadButton.style.padding = '5px 10px';
  downloadButton.style.backgroundColor = 'lightgray';
  downloadButton.style.color = 'black';
  downloadButton.setAttribute('download', fileName);
  downloadButton.setAttribute('href', window.location.href);
  document.body.appendChild(downloadButton);

 to append a download button on raw github pages , example: 
https://gist.githubusercontent.com/ale82to/8c5349090495fd7538a556bdb126320b/raw/e12766d1d262877b99215d57253940d3432f5450/test.js

but its not working at all not even the alert fun; in violentmonkey i ve no problem at all,tge  userscript is inject without any problem,what am i missing?
thanks

**Comment by erosman** [comment]
Please post to the [support](https://github.com/erosman/support).
